{
	"auto_complete":
	{
		"selected_items":
		[
			[
				"co",
				"context〔variable〕"
			],
			[
				"ur",
				"urls"
			],
			[
				"repos",
				"reposts〔variable〕"
			],
			[
				"w",
				"writelines〔function〕"
			],
			[
				"re",
				"readlines〔function〕"
			],
			[
				"data_s",
				"data_similar"
			],
			[
				"data",
				"data_traffic"
			],
			[
				"lo",
				"loads〔function〕"
			],
			[
				"t",
				"text"
			],
			[
				"th",
				"threading〔module〕"
			],
			[
				"ra",
				"raw_input〔function〕"
			],
			[
				"Soc",
				"Socials"
			],
			[
				"Re",
				"Refers"
			],
			[
				"s",
				"socket"
			],
			[
				"S",
				"socket"
			],
			[
				"spl",
				"splitext\tfunction"
			],
			[
				"d",
				"dumps"
			],
			[
				"R",
				"Rossija"
			],
			[
				"e",
				"except\tkeyword"
			],
			[
				"iter",
				"iterfind\tfunction"
			],
			[
				"fin",
				"find\tfunction"
			],
			[
				"countr",
				"country_ru\tstatement"
			],
			[
				"country",
				"country_ru\tstatement"
			],
			[
				"x",
				"xml_root\tstatement"
			],
			[
				"O",
				"Ostrova"
			],
			[
				"Kaj",
				"Kajmanovy"
			],
			[
				"ta",
				"Tajvan"
			],
			[
				"Ta",
				"Tajvan"
			],
			[
				"F",
				"Frantsuzskaja"
			],
			[
				"Tu",
				"Turkmenija"
			],
			[
				"T",
				"Turtsija"
			],
			[
				"J",
				"JuAR"
			],
			[
				"ja",
				"Japonija"
			],
			[
				"coun",
				"country_eng\tstatement"
			],
			[
				"it",
				"iter\tfunction"
			],
			[
				"db_file",
				"db_file\tstatement"
			],
			[
				"cre",
				"create"
			],
			[
				"ca",
				"cards_left_ai〔variable〕"
			],
			[
				"cards",
				"cards_left_my〔variable〕"
			],
			[
				"r",
				"randrange〔function〕"
			],
			[
				"kw",
				"kwargs_str"
			],
			[
				"url",
				"urllib.request.urlretrieve"
			],
			[
				"m",
				"mkdir〔function〕"
			],
			[
				"1",
				"1000"
			],
			[
				"random",
				"random.choice"
			],
			[
				"read",
				"readlines〔function〕"
			],
			[
				"p",
				"punctuation〔variable〕"
			],
			[
				"rea",
				"readline〔function〕"
			],
			[
				"str",
				"str.strip"
			],
			[
				"c",
				"clear〔function〕"
			],
			[
				"b",
				"b"
			]
		]
	},
	"buffers":
	[
		{
			"contents": "bash: no job control in this shell\nbash-3.2$ cd ~\nbash-3.2$ cd Documents\nbash-3.2$ cd learning_log\nbash-3.2$ ls\ndb.sqlite3\nlearning_log\nll_env\nmanage.py\nbash-3.2$ source ll_env/bin/activate\n(ll_env) bash-3.2$ python manage.py runserver\n[30/Nov/2016 11:12:00] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 11:20:36] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 11:20:37] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 11:11:58\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 11:45:32] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 11:52:01] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 11:40:20\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 11:54:14] \"GET /admin HTTP/1.1\" 301 0\n[30/Nov/2016 11:54:14] \"GET /admin/ HTTP/1.1\" 302 0\n[30/Nov/2016 11:54:14] \"GET /admin/login/?next=/admin/ HTTP/1.1\" 200 1653\n[30/Nov/2016 11:54:14] \"GET /static/admin/css/login.css HTTP/1.1\" 200 1203\n[30/Nov/2016 11:54:14] \"GET /static/admin/css/base.css HTTP/1.1\" 200 15937\n[30/Nov/2016 11:54:14] \"GET /static/admin/css/fonts.css HTTP/1.1\" 200 423\n[30/Nov/2016 11:54:14] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 200 80304\n[30/Nov/2016 11:54:14] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 200 81348\n[30/Nov/2016 11:54:43] \"POST /admin/login/?next=/admin/ HTTP/1.1\" 302 0\n[30/Nov/2016 11:54:43] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:54:44] \"GET /static/admin/css/dashboard.css HTTP/1.1\" 200 434\n[30/Nov/2016 11:54:44] \"GET /static/admin/img/icon-changelink.svg HTTP/1.1\" 200 380\n[30/Nov/2016 11:54:44] \"GET /static/admin/img/icon-addlink.svg HTTP/1.1\" 200 331\n[30/Nov/2016 11:54:44] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 200 82564\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 11:54:08\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 11:55:45] \"GET /admin/ HTTP/1.1\" 200 2782\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 11:55:45\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 11:55:56] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:56:27] \"GET /admin/auth/user/ HTTP/1.1\" 200 6355\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/core.js HTTP/1.1\" 200 7976\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 200 363\n[30/Nov/2016 11:56:27] \"GET /static/admin/css/changelists.css HTTP/1.1\" 200 6117\n[30/Nov/2016 11:56:27] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 200 6577\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/actions.js HTTP/1.1\" 200 6501\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/urlify.js HTTP/1.1\" 200 8186\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 200 1538\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 200 258648\n[30/Nov/2016 11:56:27] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 200 128820\n[30/Nov/2016 11:56:27] \"GET /static/admin/img/search.svg HTTP/1.1\" 200 458\n[30/Nov/2016 11:56:27] \"GET /static/admin/img/icon-yes.svg HTTP/1.1\" 200 436\n[30/Nov/2016 11:56:27] \"GET /static/admin/img/sorting-icons.svg HTTP/1.1\" 200 1097\n[30/Nov/2016 11:56:27] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 200 331\n[30/Nov/2016 11:56:49] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:56:50] \"GET /admin/auth/user/ HTTP/1.1\" 200 6355\n[30/Nov/2016 11:56:50] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:56:53] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:56:54] \"GET /admin/auth/group/ HTTP/1.1\" 200 3382\n[30/Nov/2016 11:56:54] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:56:56] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:57:00] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 3064\n[30/Nov/2016 11:57:00] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:57:03] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:57:04] \"GET /admin/learning_logs/topic/add/ HTTP/1.1\" 200 3837\n[30/Nov/2016 11:57:04] \"GET /static/admin/css/forms.css HTTP/1.1\" 200 7750\n[30/Nov/2016 11:57:04] \"GET /static/admin/js/change_form.js HTTP/1.1\" 200 698\n[30/Nov/2016 11:57:04] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:57:04] \"GET /static/admin/js/prepopulate_init.js HTTP/1.1\" 200 495\n[30/Nov/2016 11:57:04] \"GET /static/admin/css/widgets.css HTTP/1.1\" 200 10340\n[30/Nov/2016 11:57:10] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:57:11] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 3064\n[30/Nov/2016 11:57:11] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:57:13] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:57:14] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 3064\n[30/Nov/2016 11:57:14] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:57:17] \"GET /admin/ HTTP/1.1\" 200 3468\n[30/Nov/2016 11:57:55] \"GET /admin/auth/user/add/ HTTP/1.1\" 200 5165\n[30/Nov/2016 11:57:55] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:58:15] \"POST /admin/auth/user/add/ HTTP/1.1\" 200 5392\n[30/Nov/2016 11:58:16] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:58:24] \"POST /admin/auth/user/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 11:58:24] \"GET /admin/auth/user/2/change/ HTTP/1.1\" 200 13744\n[30/Nov/2016 11:58:24] \"GET /static/admin/js/calendar.js HTTP/1.1\" 200 7790\n[30/Nov/2016 11:58:24] \"GET /static/admin/js/SelectBox.js HTTP/1.1\" 200 5755\n[30/Nov/2016 11:58:24] \"GET /static/admin/js/SelectFilter2.js HTTP/1.1\" 200 12389\n[30/Nov/2016 11:58:24] \"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1\" 200 20529\n[30/Nov/2016 11:58:24] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:58:24] \"GET /static/admin/img/icon-unknown.svg HTTP/1.1\" 200 655\n[30/Nov/2016 11:58:24] \"GET /static/admin/img/selector-icons.svg HTTP/1.1\" 200 3291\n[30/Nov/2016 11:58:24] \"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1\" 200 655\n[30/Nov/2016 11:58:24] \"GET /static/admin/img/icon-clock.svg HTTP/1.1\" 200 677\n[30/Nov/2016 11:58:24] \"GET /static/admin/img/icon-calendar.svg HTTP/1.1\" 200 1086\n[30/Nov/2016 11:59:25] \"POST /admin/auth/user/2/change/ HTTP/1.1\" 302 0\n[30/Nov/2016 11:59:25] \"GET /admin/auth/user/ HTTP/1.1\" 200 6959\n[30/Nov/2016 11:59:25] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:59:25] \"GET /static/admin/img/icon-no.svg HTTP/1.1\" 200 560\n[30/Nov/2016 11:59:36] \"GET /admin/auth/user/?is_staff__exact=0 HTTP/1.1\" 200 6849\n[30/Nov/2016 11:59:36] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:59:39] \"GET /admin/auth/user/? HTTP/1.1\" 200 6781\n[30/Nov/2016 11:59:39] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:59:41] \"GET /admin/auth/user/?is_staff__exact=1 HTTP/1.1\" 200 6845\n[30/Nov/2016 11:59:41] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 11:59:42] \"GET /admin/auth/user/? HTTP/1.1\" 200 6781\n[30/Nov/2016 11:59:42] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:00:29] \"GET /admin/auth/ HTTP/1.1\" 200 2708\n[30/Nov/2016 12:00:30] \"GET /admin/ HTTP/1.1\" 200 4066\n[30/Nov/2016 12:00:32] \"GET /admin/auth/group/add/ HTTP/1.1\" 200 6142\n[30/Nov/2016 12:00:32] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:00:58] \"POST /admin/auth/group/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:00:58] \"GET /admin/auth/group/ HTTP/1.1\" 200 4687\n[30/Nov/2016 12:00:58] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:01:23] \"GET /admin/auth/group/1/change/ HTTP/1.1\" 200 6392\n[30/Nov/2016 12:01:23] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:01:27] \"GET /admin/auth/group/ HTTP/1.1\" 200 4512\n[30/Nov/2016 12:01:43] \"GET /admin/auth/ HTTP/1.1\" 200 2708\n[30/Nov/2016 12:01:43] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:01:43] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:01:43] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:01:43] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:01:44] \"GET /admin/auth/user/ HTTP/1.1\" 200 6987\n[30/Nov/2016 12:01:44] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:01:47] \"GET /admin/auth/user/2/change/ HTTP/1.1\" 200 13621\n[30/Nov/2016 12:01:47] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:01:54] \"POST /admin/auth/user/2/change/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:01:54] \"GET /admin/auth/user/ HTTP/1.1\" 200 7165\n[30/Nov/2016 12:01:55] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:02:47] \"GET /admin/auth/ HTTP/1.1\" 200 2708\n[30/Nov/2016 12:02:47] \"GET /static/admin/css/dashboard.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:02:47] \"GET /static/admin/img/icon-addlink.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:02:47] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:02:47] \"GET /static/admin/img/icon-changelink.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:02:48] \"GET /admin/auth/group/ HTTP/1.1\" 200 4512\n[30/Nov/2016 12:02:48] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:02:49] \"GET /admin/auth/group/1/change/ HTTP/1.1\" 200 6392\n[30/Nov/2016 12:02:50] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:03:04] \"POST /admin/auth/group/1/change/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:03:04] \"GET /admin/auth/group/ HTTP/1.1\" 200 4689\n[30/Nov/2016 12:03:04] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:03:39] \"GET /admin/ HTTP/1.1\" 200 4913\n[30/Nov/2016 12:04:36] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 3064\n[30/Nov/2016 12:04:36] \"GET /static/admin/css/changelists.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/core.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/actions.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/urlify.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:36] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:38] \"GET /admin/learning_logs/topic/add/ HTTP/1.1\" 200 3837\n[30/Nov/2016 12:04:38] \"GET /static/admin/css/forms.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:38] \"GET /static/admin/js/change_form.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:38] \"GET /static/admin/js/prepopulate_init.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:38] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:04:38] \"GET /static/admin/css/widgets.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:04:51] \"POST /admin/learning_logs/topic/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:04:51] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4387\n[30/Nov/2016 12:04:51] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:04:51] \"GET /static/admin/img/icon-yes.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:07:34] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:35] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:07:38] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:38] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:07:39] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:39] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:07:40] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:40] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:07:41] \"GET /admin/learning_logs/ HTTP/1.1\" 200 2285\n[30/Nov/2016 12:07:42] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:42] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:07:43] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:43] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:07:44] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4203\n[30/Nov/2016 12:07:44] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:08:17] \"GET /admin/learning_logs/topic/add/ HTTP/1.1\" 200 3837\n[30/Nov/2016 12:08:17] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:08:22] \"POST /admin/learning_logs/topic/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:08:22] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4612\n[30/Nov/2016 12:08:22] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:09:07] \"GET /admin/learning_logs/topic/2/change/ HTTP/1.1\" 200 4083\n[30/Nov/2016 12:09:07] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:09:09] \"GET /admin/learning_logs/topic/2/delete/ HTTP/1.1\" 200 3024\n[30/Nov/2016 12:09:09] \"GET /static/admin/js/cancel.js HTTP/1.1\" 200 204\n[30/Nov/2016 12:09:11] \"POST /admin/learning_logs/topic/2/delete/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:09:11] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4347\n[30/Nov/2016 12:09:11] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:09:48] \"GET /admin/learning_logs/topic/add/ HTTP/1.1\" 200 3837\n[30/Nov/2016 12:09:48] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:09:48] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:09:48] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:09:48] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:09:48] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:09:51] \"POST /admin/learning_logs/topic/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:09:51] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4630\n[30/Nov/2016 12:09:51] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 11:55:56\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:13:18\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:18:45\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 12:20:23] \"GET /admin/ HTTP/1.1\" 200 6442\n[30/Nov/2016 12:20:23] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:23] \"GET /static/admin/css/dashboard.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:23] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:24] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:24] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:24] \"GET /static/admin/img/icon-addlink.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:24] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:24] \"GET /static/admin/img/icon-changelink.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:24] \"GET /static/admin/img/icon-deletelink.svg HTTP/1.1\" 200 392\n[30/Nov/2016 12:20:45] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 3066\n[30/Nov/2016 12:20:45] \"GET /static/admin/css/changelists.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/core.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/actions.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/urlify.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:45] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:20:46] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:50] \"GET /admin/learning_logs/entry/add/ HTTP/1.1\" 200 5125\n[30/Nov/2016 12:20:50] \"GET /static/admin/css/forms.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:50] \"GET /static/admin/js/change_form.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:50] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:20:50] \"GET /static/admin/js/prepopulate_init.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:20:50] \"GET /static/admin/css/widgets.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:22:19] \"POST /admin/learning_logs/entry/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:22:20] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4403\n[30/Nov/2016 12:22:20] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:22:20] \"GET /static/admin/img/icon-yes.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:22:44] \"GET /admin/learning_logs/ HTTP/1.1\" 200 2700\n[30/Nov/2016 12:22:45] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4212\n[30/Nov/2016 12:22:45] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:22:47] \"GET /admin/learning_logs/entry/1/change/ HTTP/1.1\" 200 5996\n[30/Nov/2016 12:22:47] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:22:50] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4212\n[30/Nov/2016 12:22:53] \"GET /admin/learning_logs/entry/1/change/ HTTP/1.1\" 200 5996\n[30/Nov/2016 12:22:53] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:23:04] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4212\n[30/Nov/2016 12:23:04] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:23:05] \"GET /admin/ HTTP/1.1\" 200 6738\n[30/Nov/2016 12:23:10] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4212\n[30/Nov/2016 12:23:10] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:23:11] \"GET /admin/learning_logs/entry/1/change/ HTTP/1.1\" 200 5996\n[30/Nov/2016 12:23:11] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:23:59] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4212\n[30/Nov/2016 12:23:59] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:24:02] \"GET /admin/learning_logs/entry/add/ HTTP/1.1\" 200 5125\n[30/Nov/2016 12:24:02] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:24:37] \"POST /admin/learning_logs/entry/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:24:37] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4638\n[30/Nov/2016 12:24:37] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:20:19\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 12:25:28] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:25:28] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:25:29] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:25:29] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:25:31] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:25:31] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:25:31] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:25:31] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:25:32] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:25:32] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:24:52\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 12:26:10] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:26:10] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:26:12] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:26:12] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:26:13] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4447\n[30/Nov/2016 12:26:13] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:25:58\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:26:47\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 12:27:22] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4561\n[30/Nov/2016 12:27:22] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:28:15] \"GET /admin/learning_logs/entry/add/ HTTP/1.1\" 200 5118\n[30/Nov/2016 12:28:15] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:28:19] \"POST /admin/learning_logs/entry/add/ HTTP/1.1\" 302 0\n[30/Nov/2016 12:28:19] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 5019\n[30/Nov/2016 12:28:19] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:27:20\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 12:29:39] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4808\n[30/Nov/2016 12:29:39] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:29:42] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4808\n[30/Nov/2016 12:29:42] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:29:36\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 12:29:54] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4808\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/core.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/css/changelists.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/actions.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/urlify.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:29:54] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:54] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:29:55] \"GET /admin/learning_logs/entry/ HTTP/1.1\" 200 4808\n[30/Nov/2016 12:29:55] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:51:07] \"GET /admin/learning_logs/ HTTP/1.1\" 200 2700\n[30/Nov/2016 12:51:07] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/css/dashboard.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/img/icon-addlink.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:07] \"GET /static/admin/img/icon-changelink.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4676\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/core.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/css/changelists.css HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/urlify.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/actions.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:51:09] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 304 0\n[30/Nov/2016 12:51:09] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 304 0\n[30/Nov/2016 12:52:18] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4669\n[30/Nov/2016 12:52:18] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 12:55:22] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 12:55:22] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 12:29:53\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1045b7bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\n[30/Nov/2016 13:22:58] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:00] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:00] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:01] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:01] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:22:58\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 13:23:09] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:10] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:11] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:12] \"GET / HTTP/1.1\" 200 1767\n[30/Nov/2016 13:23:14] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:23:05\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1036b7bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\n[30/Nov/2016 13:30:51] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:30:51] \"GET /static/admin/css/changelists.css HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/core.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/actions.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/urlify.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:51] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:52] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:52] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:52] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:52] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 304 0\n[30/Nov/2016 13:30:55] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:30:43\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1047dfbf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'^$', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x103eb7bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\n[30/Nov/2016 13:31:52] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:31:51\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 13:39:13] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:39:13] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:35:55\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x103edfbf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\n[30/Nov/2016 13:39:38] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:39:38] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:39:37\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 13:39:43] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 1767\n[30/Nov/2016 13:39:45] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 1767\n[30/Nov/2016 13:39:45] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 1767\n[30/Nov/2016 13:39:46] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 1767\n[30/Nov/2016 13:39:46] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:39:42\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:39:50\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1058dfbf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x103edfbf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x105fb7bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1055b2bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\nNameError: name 'include' is not defined\nPerforming system checks...\n\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1047b7bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', learning_logs.urls, namespace='learning_logs'),\nNameError: name 'learning_logs' is not defined\nPerforming system checks...\n\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x104eb2bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', learning_logs.urls),\nNameError: name 'learning_logs' is not defined\nPerforming system checks...\n\n[30/Nov/2016 13:47:48] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:47:47\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x104db2bf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 20, in <module>\n    url(r'^admin/', include(admin.site.urls)),\nNameError: name 'include' is not defined\nPerforming system checks...\n\n[30/Nov/2016 13:50:09] \"GET / HTTP/1.1\" 200 1767\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:50:09\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 13:52:11] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:11] \"GET /static/admin/css/changelists.css HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/css/base.css HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/core.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/jquery.init.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/actions.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/urlify.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/prepopulate.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/css/fonts.css HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 304 0\n[30/Nov/2016 13:52:11] \"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 304 0\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:52:06\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 13:52:22] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:22] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:24] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:24] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:24] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:24] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:25] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:25] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:26] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:26] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:26] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:26] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:27] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:27] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:52:27] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:52:27] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:52:21\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 13:53:00] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:53:00] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:53:00] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:53:00] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:53:01] \"GET /admin/learning_logs/topic/ HTTP/1.1\" 200 4438\n[30/Nov/2016 13:53:01] \"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\n[30/Nov/2016 13:53:04] \"GET / HTTP/1.1\" 200 115\n[30/Nov/2016 13:53:30] \"GET / HTTP/1.1\" 200 115\n[30/Nov/2016 13:53:30] \"GET / HTTP/1.1\" 200 115\n[30/Nov/2016 13:53:31] \"GET / HTTP/1.1\" 200 115\n[30/Nov/2016 13:53:31] \"GET / HTTP/1.1\" 200 115\n[30/Nov/2016 14:13:02] \"GET / HTTP/1.1\" 200 136\n[30/Nov/2016 14:13:03] \"GET / HTTP/1.1\" 200 136\n[30/Nov/2016 14:13:04] \"GET / HTTP/1.1\" 200 136\n[30/Nov/2016 14:14:24] \"GET / HTTP/1.1\" 200 39\n[30/Nov/2016 14:14:36] \"GET / HTTP/1.1\" 200 136\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 13:53:00\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 14:16:14] \"GET / HTTP/1.1\" 200 39\n[30/Nov/2016 14:16:14] \"GET / HTTP/1.1\" 200 39\n[30/Nov/2016 14:16:15] \"GET / HTTP/1.1\" 200 39\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:16:12\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 14:16:32] \"GET / HTTP/1.1\" 200 136\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:16:31\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1060dfbf8>\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 121, in inner_run\n    self.check(display_num_errors=True)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 374, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py\", line 361, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n    return check_resolver(resolver)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n    for pattern in resolver.url_patterns:\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 313, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py\", line 306, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_log/urls.py\", line 21, in <module>\n    url(r'', include('learning_logs.urls', namespace='learning_logs')),\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/conf/urls/__init__.py\", line 50, in include\n    urlconf_module = import_module(urlconf_module)\n  File \"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/pavlo/Documents/learning_log/learning_logs/urls.py\", line 8, in <module>\n    url(r'^topics/$', views.topics, name='topics'),\nAttributeError: module 'learning_logs.views' has no attribute 'topics'\nPerforming system checks...\n\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:22:38\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:23:50\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:23:58\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:28:10\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 14:35:54] \"GET / HTTP/1.1\" 200 168\n[30/Nov/2016 14:36:12] \"GET /topics/ HTTP/1.1\" 200 162\n[30/Nov/2016 14:36:14] \"GET / HTTP/1.1\" 200 168\n[30/Nov/2016 14:36:16] \"GET /topics/ HTTP/1.1\" 200 162\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:31:38\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\nPerforming system checks...\n\nSystem check identified no issues (0 silenced).\nNovember 30, 2016 - 14:45:01\nDjango version 1.10.3, using settings 'learning_log.settings'\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n[30/Nov/2016 14:55:58] \"GET /topics/ HTTP/1.1\" 200 162\n[30/Nov/2016 14:56:01] \"GET /topics/1/ HTTP/1.1\" 200 3145\nInternal Server Error: /topics/2/\nTraceback (most recent call last):\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/handlers/exception.py\", line 39, in inner\n    response = get_response(request)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/handlers/base.py\", line 187, in _get_response\n    response = self.process_exception_by_middleware(e, request)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/core/handlers/base.py\", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Users/pavlo/Documents/learning_log/learning_logs/views.py\", line 15, in topic\n    topic = Topic.objects.get(id=topic_id)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/Users/pavlo/Documents/learning_log/ll_env/lib/python3.5/site-packages/django/db/models/query.py\", line 385, in get\n    self.model._meta.object_name\nlearning_logs.models.DoesNotExist: Topic matching query does not exist.\n[30/Nov/2016 14:56:14] \"GET /topics/2/ HTTP/1.1\" 500 69580\n[30/Nov/2016 14:56:20] \"GET /topics/3/ HTTP/1.1\" 200 223\n[30/Nov/2016 14:56:24] \"GET /topics/ HTTP/1.1\" 200 162\n[30/Nov/2016 14:58:38] \"GET /topics/ HTTP/1.1\" 200 212\n",
			"settings":
			{
				"buffer_size": 78788,
				"line_ending": "Unix",
				"name": "*REPL* [shell]",
				"read_only": true,
				"scratch": true
			}
		},
		{
			"file": "models.py",
			"settings":
			{
				"buffer_size": 604,
				"encoding": "UTF-8",
				"line_ending": "Unix"
			}
		},
		{
			"file": "forms.py",
			"settings":
			{
				"buffer_size": 159,
				"encoding": "UTF-8",
				"line_ending": "Unix"
			}
		}
	],
	"build_system": "",
	"build_system_choices":
	[
	],
	"build_varint": "",
	"command_palette":
	{
		"height": 367.0,
		"last_filter": "Package Control: ",
		"selected_items":
		[
			[
				"Package Control: ",
				"Package Control: Remove Package"
			],
			[
				"insta",
				"Package Control: Install Package"
			]
		],
		"width": 593.0
	},
	"console":
	{
		"height": 0.0,
		"history":
		[
		]
	},
	"distraction_free":
	{
		"menu_visible": true,
		"show_minimap": false,
		"show_open_files": false,
		"show_tabs": false,
		"side_bar_visible": false,
		"status_bar_visible": false
	},
	"expanded_folders":
	[
		"/Users/pavlo/Documents/learning_log",
		"/Users/pavlo/Documents/learning_log/learning_logs",
		"/Users/pavlo/Documents/learning_log/learning_logs/templates",
		"/Users/pavlo/Documents/learning_log/learning_logs/templates/learning_logs"
	],
	"file_history":
	[
		"/Users/pavlo/Documents/vk/konkurs.py",
		"/Users/pavlo/Documents/vk/vk1.py",
		"/Users/pavlo/Documents/fashion/base_to_xls.py",
		"/Users/pavlo/Documents/fashion/base_create.py",
		"/Users/pavlo/Documents/learning_log/learning_logs/templates/learning_logs/index.html",
		"/Users/pavlo/Documents/learning_log/learning_logs/templates/learning_logs/base.html",
		"/Users/pavlo/Documents/learning_log/learning_logs/templates/learning_logs/topics.html",
		"/Users/pavlo/Documents/learning_log/learning_logs/templates/learning_logs/topic.html",
		"/Users/pavlo/Documents/learning_log/learning_logs/views.py",
		"/Users/pavlo/Documents/learning_log/learning_log/settings.py",
		"/Users/pavlo/Documents/learning_log/learning_logs/admin.py",
		"/Users/pavlo/Documents/learning_log/learning_logs/urls.py",
		"/Users/pavlo/Documents/learning_log/manage.py",
		"/Users/pavlo/Documents/learning_log/learning_log/urls.py",
		"/Users/pavlo/Documents/learning_log/learning_logs/migrations/0001_initial.py",
		"/Users/pavlo/Documents/learning_log/learning_log/wsgi.py",
		"/Users/pavlo/Documents/test/test.py",
		"/Users/pavlo/Desktop/python/methods",
		"/Users/pavlo/Documents/vk/test.py",
		"/Users/pavlo/Documents/files/file2.txt",
		"/Users/pavlo/Documents/xls/xls-combine.py",
		"/Users/pavlo/Documents/files/files-compare.py",
		"/Users/pavlo/Documents/files/test.py",
		"/Users/pavlo/Documents/test/sites.txt",
		"/Users/pavlo/Documents/test/sites2.txt",
		"/Users/pavlo/Documents/test/result-bad.txt",
		"/Users/pavlo/Documents/test/result-good.txt",
		"/Users/pavlo/Documents/test/result.txt",
		"/Users/pavlo/Documents/test2.py",
		"/Users/pavlo/Documents/similarweb/refresh_rate.py",
		"/Users/pavlo/Documents/alexa/aud-overlap.py",
		"/Users/pavlo/Work/Arbitrage/html/Redirects/js.html",
		"/Users/pavlo/Work/Arbitrage/html/Redirects/meta.html",
		"/Users/pavlo/Desktop/favicon.ico",
		"/Users/pavlo/Desktop/python/commands",
		"/Users/pavlo/Documents/test.py",
		"/Users/pavlo/Documents/vk1.py",
		"/Users/pavlo/Sites/www/vk.php",
		"/Users/pavlo/Documents/vk.py",
		"/Users/pavlo/Documents/fashion/test.py",
		"/Users/pavlo/Documents/alexa/test3.py",
		"/Users/pavlo/Documents/test3.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/lesson7/exercises/weather.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/lesson7/5_json.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 4. Системное программирование/lesson4/exercises/babynames/babynames — копия 2.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/lesson7/exercises/export_weather.py",
		"/Users/pavlo/Documents/fashion/base.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/lesson7/3_csv.py",
		"/Users/pavlo/Sites/www/index.php",
		"/Users/pavlo/Documents/result.csv",
		"/Users/pavlo/Documents/employees_out.csv",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/exercises/babynames/babynames.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 4. Системное программирование/lesson4/exercises/logpuzzle/logpuzzle — копия 2.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/lesson7/4_sqlite.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 6. Декораторы, Исключения, Итераторы/geometry/main.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 7. Библиотеки/lesson7/6_xml.py",
		"/Users/pavlo/Downloads/transliterate-1.8.1/README.rst",
		"/Users/pavlo/Documents/cities.db-journal",
		"/Users/pavlo/Documents/cities.db",
		"/Users/pavlo/Library/Application Support/Sublime Text 3/Packages/Anaconda/Anaconda.sublime-settings",
		"/Users/pavlo/Library/Application Support/Sublime Text 3/Packages/User/Anaconda.sublime-settings",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 6. Декораторы, Исключения, Итераторы/lesson6/execrises/loto.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 5. Модули, пакеты, классы и объекты/lesson5/3_class.py",
		"/Users/pavlo/Documents/logpuzzle.py",
		"/Users/pavlo/Documents/babynames.py",
		"/Users/pavlo/Documents/geometry.py",
		"/Users/pavlo/Documents/flat.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 3. Функциональное программирование/lesson3/exercises/euler2.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 3. Функциональное программирование/lesson3/exercises/euler1.py",
		"/Users/pavlo/Documents/mimic.py",
		"/Users/pavlo/Documents/wordcount.py",
		"/Users/pavlo/Documents/babynames_girls.html",
		"/Users/pavlo/Documents/apple-cat.ru_access.log",
		"/Users/pavlo/Documents/babynames_boys.html",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 3. Функциональное программирование/exercises/wordcount.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 1. Введение/lesson1/exercises/list.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 2. Структуры данных/lesson2/exercises/wordcount.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 1. Введение/lesson1/exercises/slice.py",
		"/Users/pavlo/Downloads/Школа программирования - Python. Основы языка и разработки веб-приложений (2015)/Урок 1. Введение/lesson1/exercises/string.py",
		"/Users/pavlo/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings",
		"/Users/pavlo/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
	],
	"find":
	{
		"height": 35.0
	},
	"find_in_files":
	{
		"height": 0.0,
		"where_history":
		[
		]
	},
	"find_state":
	{
		"case_sensitive": false,
		"find_history":
		[
			"lorem500",
			"luckybrand",
			"laredoute",
			"modcloth",
			", ",
			"0.35014111807342252",
			"visits",
			".path",
			"join",
			"906609",
			"line",
			"end",
			"check\\",
			"check",
			"update"
		],
		"highlight": true,
		"in_selection": false,
		"preserve_case": true,
		"regex": true,
		"replace_history":
		[
			"\\n",
			"word"
		],
		"reverse": false,
		"show_context": true,
		"use_buffer2": true,
		"whole_word": false,
		"wrap": true
	},
	"groups":
	[
		{
			"selected": 2,
			"sheets":
			[
				{
					"buffer": 0,
					"semi_transient": false,
					"settings":
					{
						"buffer_size": 78788,
						"regions":
						{
						},
						"selection":
						[
							[
								76044,
								76044
							]
						],
						"settings":
						{
							"auto_complete": true,
							"auto_indent": false,
							"detect_indentation": false,
							"gutter": false,
							"history_arrows": true,
							"indent_subsequent_lines": false,
							"line_numbers": false,
							"repl": true,
							"repl_external_id": "shell",
							"repl_id": "68c2f8f605e14b199efe02e4e71818b7",
							"repl_restart_args":
							{
								"cmd":
								{
									"linux":
									[
										"bash",
										"-i"
									],
									"osx":
									[
										"bash",
										"-i"
									],
									"windows":
									[
										"cmd.exe"
									]
								},
								"cmd_postfix": "\n",
								"cwd": "$file_path",
								"encoding":
								{
									"linux": "utf-8",
									"osx": "utf-8",
									"windows": "$win_cmd_encoding"
								},
								"env":
								{
								},
								"external_id": "shell",
								"suppress_echo": true,
								"syntax": "Packages/Text/Plain text.tmLanguage",
								"type": "subprocess"
							},
							"repl_sublime2": false,
							"smart_indent": false,
							"spell_check": false,
							"syntax": "Packages/ShellScript/Shell-Unix-Generic.sublime-syntax",
							"translate_tabs_to_spaces": false
						},
						"translation.x": 0.0,
						"translation.y": 16646.0,
						"zoom_level": 1.0
					},
					"stack_index": 2,
					"type": "text"
				},
				{
					"buffer": 1,
					"file": "models.py",
					"semi_transient": false,
					"settings":
					{
						"buffer_size": 604,
						"regions":
						{
						},
						"selection":
						[
							[
								588,
								588
							]
						],
						"settings":
						{
							"auto_complete": false,
							"syntax": "Packages/Python/Python.sublime-syntax"
						},
						"translation.x": 0.0,
						"translation.y": 0.0,
						"zoom_level": 1.0
					},
					"stack_index": 1,
					"type": "text"
				},
				{
					"buffer": 2,
					"file": "forms.py",
					"semi_transient": false,
					"settings":
					{
						"buffer_size": 159,
						"regions":
						{
						},
						"selection":
						[
							[
								159,
								159
							]
						],
						"settings":
						{
							"auto_complete": false,
							"syntax": "Packages/Python/Python.sublime-syntax",
							"translate_tabs_to_spaces": false
						},
						"translation.x": 0.0,
						"translation.y": 0.0,
						"zoom_level": 1.0
					},
					"stack_index": 0,
					"type": "text"
				}
			]
		}
	],
	"incremental_find":
	{
		"height": 23.0
	},
	"input":
	{
		"height": 0.0
	},
	"layout":
	{
		"cells":
		[
			[
				0,
				0,
				1,
				1
			]
		],
		"cols":
		[
			0.0,
			1.0
		],
		"rows":
		[
			0.0,
			1.0
		]
	},
	"menu_visible": true,
	"output.find_results":
	{
		"height": 0.0
	},
	"pinned_build_system": "",
	"project": "ll.sublime-project",
	"replace":
	{
		"height": 64.0
	},
	"save_all_on_build": true,
	"select_file":
	{
		"height": 0.0,
		"last_filter": "",
		"selected_items":
		[
		],
		"width": 0.0
	},
	"select_project":
	{
		"height": 0.0,
		"last_filter": "",
		"selected_items":
		[
		],
		"width": 0.0
	},
	"select_symbol":
	{
		"height": 0.0,
		"last_filter": "",
		"selected_items":
		[
		],
		"width": 0.0
	},
	"selected_group": 0,
	"settings":
	{
	},
	"show_minimap": false,
	"show_open_files": false,
	"show_tabs": true,
	"side_bar_visible": true,
	"side_bar_width": 194.0,
	"status_bar_visible": true,
	"template_settings":
	{
	}
}
